name: MyCI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UV_CACHE_DIR: .uv-cache
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DJANGO_SETTINGS_MODULE: task_manager.settings
  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
  ROLLBAR_ENV: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: '3.13'

    - name: Setup uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        python-version: '3.13'

    - name: Install & Lint
      run: |
        make install
        make check
        make format

    - name: Tests + Coverage
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@e5145fe946c1c3f196ebbf0a89803eec047c24fe
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.projectKey=annetmyshkina_python-project-52
          -Dsonar.organization=annetmyshkina
          -Dsonar.python.coverage.reportPaths=coverage.xml

    - name: Upload SonarQube metadata
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: sonar-report
        path: .scannerwork/report-task.txt
        retention-days: 1

  quality-gate:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Download SonarQube metadata
      uses: actions/download-artifact@v4
      with:
        name: sonar-report

    - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
