# Generated by Django 6.0.2 on 2026-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Name"),
        ),
    ]
